const SUPABASE_URL = https://riizbppmwhkntotukbga.supabase.co/rest/v1/
const SUPABASE_ANON_key =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpaXpicHBtd2hrbnRvdHVrYmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3MjkzNjcsImV4cCI6MjEwMzMwNTM2N30.3ATHYOmxFcujbKoAAgezzMBL9qr7JKY_49gXevHAh58;
